name: Test (Pull and Validate Docker Image)

on:
  workflow_run:
    workflows: ["Train (Build and Push Docker Image)"]
    types: [completed]

jobs:
  validate-docker-image:
    name: Validate Docker Image
    runs-on: ubuntu-latest
    #needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull jacsdocker/cicd_assignment:latest

      - name: Run Docker container
        run: docker run jacsdocker/cicd_assignment:latest

      - name: Extract and validate score
        run: |
          output_score=$(docker run jacsdocker/cicd_assignment:latest | grep -oP '0\.\d+')
          if (( $(echo "$output_score > 0.30" | bc -l) )); then
            echo "Score is greater than 0.30"
            exit 0
          else
            echo "Score is less than or equal to 0.30"
            exit 1
          fi
