name: Test (Pull and Validate Docker Image)

on:
  workflow_run:
    workflows: ["Train (Build and Push Docker Image)"]
    types: [completed]

jobs:
  validate-docker-image:
    name: Validate Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Debug Information
        run: |
          echo "Workflow run triggered"
          echo "Workflow: ${{ github.event.workflow_run.workflow }}"
          echo "Event: ${{ toJson(github.event) }}"