name: Pull Docker Image and Validate Score

on:
  pull_request:
    branches:
      - main
      - both-action-success

jobs:
  pull-and-validate:
    name: Pull and Validate
    runs-on: ubuntu-latest
    needs: build-and-push
    if: ${{ needs.build-and-push.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull abrahamjacobm/CICD_Assignment:${{ needs.build-and-push.outputs.docker_image_tag }}

      - name: Run Docker container
        run: docker run abrahamjacobm/CICD_Assignment:${{ needs.build-and-push.outputs.docker_image_tag }}

      - name: Extract and validate score
        run: |
          output_score=$(docker run abrahamjacobm/CICD_Assignment:${{ needs.build-and-push.outputs.docker_image_tag }} | grep -oP '0\.\d+')
          if (( $(echo "$output_score > 0.30" | bc -l) )); then
            echo "Score is greater than 0.30"
            exit 0
          else
            echo "Score is less than or equal to 0.30"
            exit 1
          fi
