name: Test (Pull Docker Image and Validate Score)

on:
  pull_request:
    branches:
      - main
      - both-action-success

jobs:
  pull-and-validate:
    name: Pull Docker Image and Validate Score
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull abrahamjacobm/CICD_Assignment:latest

      - name: Run Docker container
        run: docker run abrahamjacobm/CICD_Assignment:latest

      - name: Extract and validate score
        run: |
          output_score=$(docker run abrahamjacobm/CICD_Assignment:latest | grep -oP '0\.\d+')
          if (( $(echo "$output_score > 0.30" | bc -l) )); then
            echo "Score is greater than 0.30"
            exit 0
          else
            echo "Score is less than or equal to 0.30"
            exit 1
          fi
