name: Test

on:
  workflow_run:
    workflows:
      - "Train"
    types:
      - completed
  pull_request:
    branches:
      - main
      - both-action-success

jobs:
  dummy-job:
    name: Dummy Job (Independent)
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "This is a dummy job for workflow trigger."

  validate-docker-image:
    name: Validate Docker Image
    runs-on: ubuntu-latest
    needs: dummy-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull jacsdocker/cicd_assignment:latest

      - name: Run Docker container
        run: docker run jacsdocker/cicd_assignment:latest

      - name: Extract and validate score
        run: |
          output_score=$(docker run jacsdocker/cicd_assignment:latest | grep -oP '0\.\d+')
          if (( $(echo "$output_score > 0.30" | bc -l) )); then
            echo "Ok Score is greater than 0.30"
            exit 0
          else
            echo "Score is less than or equal to 0.30"
            exit 1
          fi