name: Run Docker Image and Validate Score

on:
  pull_request:
    branches:
      - main

jobs:
  run-and-validate:
    name: Test
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Pull Docker image
        run: docker pull abrahamjacobm/CICD_Assignment:latest

      - name: Run Docker container
        run: |
          docker run abrahamjacobm/CICD_Assignment:latest

      - name: Extract and validate score
        run: |
          output_score=$(docker run abrahamjacobm/CICD_Assignment:latest | grep -oP '0\.\d+')
          if (( $(echo "$output_score > 0.50" | bc -l) )); then
            echo "Score is greater than 0.50"
            exit 0
          else
            echo "Score is less than or equal to 0.50"
            exit 1
          fi
